/* automatically generated by scripts/bindgen_rtw.sh — do not edit by hand */
/* W1-01 allowlisted bindings: AES encrypt API for the aes-ctr pilot */


pub const AES_BLOCK_SIZE: u32 = 16;
extern "C" {
    pub fn aes_encrypt_init(key: *const u8, len: usize) -> *mut core::ffi::c_void;
}
extern "C" {
    pub fn aes_encrypt(
        ctx: *mut core::ffi::c_void,
        plain: *const u8,
        crypt: *mut u8,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn aes_encrypt_deinit(ctx: *mut core::ffi::c_void);
}
