/* automatically generated by rust-bindgen 0.65.1 */

/* SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause */
/* @generated by scripts/bindgen_rtw.sh — do not edit by hand. */

pub const AES_BLOCK_SIZE: u32 = 16;
extern "C" {
    pub fn aes_encrypt_init(key: *const u8, len: usize) -> *mut core::ffi::c_void;
}
extern "C" {
    pub fn aes_encrypt(
        ctx: *mut core::ffi::c_void,
        plain: *const u8,
        crypt: *mut u8,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn aes_encrypt_deinit(ctx: *mut core::ffi::c_void);
}
extern "C" {
    pub fn aes_decrypt_init(key: *const u8, len: usize) -> *mut core::ffi::c_void;
}
extern "C" {
    pub fn aes_decrypt(
        ctx: *mut core::ffi::c_void,
        crypt: *const u8,
        plain: *mut u8,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn aes_decrypt_deinit(ctx: *mut core::ffi::c_void);
}
