/* SPDX-License-Identifier: GPL-2.0 */
#ifndef HOST_MP_PMAC_RATE_H
#define HOST_MP_PMAC_RATE_H

typedef enum _MPT_RATE_INDEX {
	MPT_RATE_1M = 1,
	MPT_RATE_2M,
	MPT_RATE_55M,
	MPT_RATE_11M,
	MPT_RATE_6M,
	MPT_RATE_9M,
	MPT_RATE_12M,
	MPT_RATE_18M,
	MPT_RATE_24M,
	MPT_RATE_36M,
	MPT_RATE_48M,
	MPT_RATE_54M,
	MPT_RATE_MCS0,
	MPT_RATE_MCS1,
	MPT_RATE_MCS2,
	MPT_RATE_MCS3,
	MPT_RATE_MCS4,
	MPT_RATE_MCS5,
	MPT_RATE_MCS6,
	MPT_RATE_MCS7,
	MPT_RATE_MCS8,
	MPT_RATE_MCS9,
	MPT_RATE_MCS10,
	MPT_RATE_MCS11,
	MPT_RATE_MCS12,
	MPT_RATE_MCS13,
	MPT_RATE_MCS14,
	MPT_RATE_MCS15,
	MPT_RATE_MCS16,
	MPT_RATE_MCS17,
	MPT_RATE_MCS18,
	MPT_RATE_MCS19,
	MPT_RATE_MCS20,
	MPT_RATE_MCS21,
	MPT_RATE_MCS22,
	MPT_RATE_MCS23,
	MPT_RATE_MCS24,
	MPT_RATE_MCS25,
	MPT_RATE_MCS26,
	MPT_RATE_MCS27,
	MPT_RATE_MCS28,
	MPT_RATE_MCS29,
	MPT_RATE_MCS30,
	MPT_RATE_MCS31,
	MPT_RATE_VHT1SS_MCS0 = 100,
	MPT_RATE_VHT1SS_MCS1,
	MPT_RATE_VHT1SS_MCS2,
	MPT_RATE_VHT1SS_MCS3,
	MPT_RATE_VHT1SS_MCS4,
	MPT_RATE_VHT1SS_MCS5,
	MPT_RATE_VHT1SS_MCS6,
	MPT_RATE_VHT1SS_MCS7,
	MPT_RATE_VHT1SS_MCS8,
	MPT_RATE_VHT1SS_MCS9,
	MPT_RATE_VHT2SS_MCS0,
	MPT_RATE_VHT2SS_MCS1,
	MPT_RATE_VHT2SS_MCS2,
	MPT_RATE_VHT2SS_MCS3,
	MPT_RATE_VHT2SS_MCS4,
	MPT_RATE_VHT2SS_MCS5,
	MPT_RATE_VHT2SS_MCS6,
	MPT_RATE_VHT2SS_MCS7,
	MPT_RATE_VHT2SS_MCS8,
	MPT_RATE_VHT2SS_MCS9,
	MPT_RATE_VHT3SS_MCS0,
	MPT_RATE_VHT3SS_MCS1,
	MPT_RATE_VHT3SS_MCS2,
	MPT_RATE_VHT3SS_MCS3,
	MPT_RATE_VHT3SS_MCS4,
	MPT_RATE_VHT3SS_MCS5,
	MPT_RATE_VHT3SS_MCS6,
	MPT_RATE_VHT3SS_MCS7,
	MPT_RATE_VHT3SS_MCS8,
	MPT_RATE_VHT3SS_MCS9,
	MPT_RATE_VHT4SS_MCS0,
	MPT_RATE_VHT4SS_MCS1,
	MPT_RATE_VHT4SS_MCS2,
	MPT_RATE_VHT4SS_MCS3,
	MPT_RATE_VHT4SS_MCS4,
	MPT_RATE_VHT4SS_MCS5,
	MPT_RATE_VHT4SS_MCS6,
	MPT_RATE_VHT4SS_MCS7,
	MPT_RATE_VHT4SS_MCS8,
	MPT_RATE_VHT4SS_MCS9,
	MPT_RATE_LAST
} MPT_RATE_INDEX;

#define MPT_IS_CCK_RATE(_value) (MPT_RATE_1M <= (_value) && (_value) <= MPT_RATE_11M)
#define MPT_IS_OFDM_RATE(_value) (MPT_RATE_6M <= (_value) && (_value) <= MPT_RATE_54M)
#define MPT_IS_HT_RATE(_value) (MPT_RATE_MCS0 <= (_value) && (_value) <= MPT_RATE_MCS31)
#define MPT_IS_VHT_RATE(_value) \
	(MPT_RATE_VHT1SS_MCS0 <= (_value) && (_value) <= MPT_RATE_VHT4SS_MCS9)
#define MPT_IS_VHT_2S_RATE(_value) \
	(MPT_RATE_VHT2SS_MCS0 <= (_value) && (_value) <= MPT_RATE_VHT2SS_MCS9)
#define MPT_IS_VHT_3S_RATE(_value) \
	(MPT_RATE_VHT3SS_MCS0 <= (_value) && (_value) <= MPT_RATE_VHT3SS_MCS9)
#define MPT_IS_VHT_4S_RATE(_value) \
	(MPT_RATE_VHT4SS_MCS0 <= (_value) && (_value) <= MPT_RATE_VHT4SS_MCS9)
#define MPT_IS_2SS_RATE(_rate) \
	((MPT_RATE_MCS8 <= (_rate) && (_rate) <= MPT_RATE_MCS15) || \
	 MPT_IS_VHT_2S_RATE(_rate))
#define MPT_IS_3SS_RATE(_rate) \
	((MPT_RATE_MCS16 <= (_rate) && (_rate) <= MPT_RATE_MCS23) || \
	 MPT_IS_VHT_3SS_RATE(_rate))
#define MPT_IS_4SS_RATE(_rate) \
	((MPT_RATE_MCS24 <= (_rate) && (_rate) <= MPT_RATE_MCS31) || \
	 MPT_IS_VHT_4SS_RATE(_rate))

#endif /* HOST_MP_PMAC_RATE_H */
