// SPDX-License-Identifier: GPL-2.0
//! Allowlisted C FFI bindings for the Wave 1 crypto pilot (W1-01).
//!
//! Generated by [`scripts/bindgen_rtw.sh`](../scripts/bindgen_rtw.sh) into
//! `rust/bindings/bindings_generated.rs`. Later translation units should
//! `include!` that file (or re-export via `rust/ffi`, W1-02) — each out-of-tree
//! `.rs` object is a separate crate under RfL kbuild.
//!
//! Linked only when the target kernel has `CONFIG_RUST=y` (see Makefile).

#![allow(
    clippy::all,
    missing_docs,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    improper_ctypes,
    unreachable_pub,
    unused_imports
)]

#[allow(dead_code)]
mod generated {
    include!("bindings/bindings_generated.rs");
}

pub use generated::*;

/// Link-time probe: proves allowlisted bindings compile into `88x2bu.ko`.
///
/// Returns [`AES_BLOCK_SIZE`] so the constant is not entirely dead. No C call
/// site yet (W1-03 will use the encrypt decls).
#[no_mangle]
pub extern "C" fn rtw_rust_bindings_probe() -> core::ffi::c_int {
    AES_BLOCK_SIZE as core::ffi::c_int
}
