// SPDX-License-Identifier: GPL-2.0
//! FFI seam: C↔Rust ownership during the mixed migration (W1-02).
//!
//! This crate is the Phase-1 **abi/ffi** edge from
//! [`docs/rust-migration/architecture.md`](../docs/rust-migration/architecture.md):
//! bindgen-backed declarations and (later) thin `extern "C"` shims. No crypto
//! or protocol logic lives here — only glue and ownership documentation.
//!
//! Linked only when the target kernel has `CONFIG_RUST=y` (see Makefile).
//!
//! # Layout
//!
//! ```text
//! rust/ffi.rs              ← this crate root (ownership map + re-exports)
//! rust/bindings/           ← bindgen helper + committed generated.rs (W1-01)
//! ```
//!
//! Each listed `.rs` is its own Kbuild crate (`rustc` resolves sibling modules
//! next to the crate root, so this file keeps the generated include in an
//! inline `mod bindings` rather than a `ffi/` directory).
//! Pilot crypto TUs (W1-03+) may `include!` `bindings/generated.rs` directly,
//! or call C-owned symbols through the same `extern "C"` names. Do not
//! duplicate *definitions*.
//!
//! # Ownership map (Wave 1)
//!
//! | Symbol / TU | Owner | Role |
//! |-------------|--------|------|
//! | `rtw_rust_kbuild_probe` | **Rust** (`kbuild_stub.rs`) | Link-only probe (W0-02) |
//! | `rtw_rust_scaffold_init` | **Rust** (`scaffold.rs`) | Called once from C init (W0-03) |
//! | `rtw_rust_bindings_probe` | **Rust** (this crate) | Confirms bindgen object linked (W1-01) |
//! | `rtw_rust_domain_types_probe` | **Rust** (`domain_types.rs`) | Confirms domain types linked (A1) |
//! | `aes_encrypt_*` / `aes_decrypt_*` / `AES_BLOCK_SIZE` | **C** (`aes-internal*.c`, `aes.h`) | Rust **binds** only — calls into C |
//! | `aes_ctr_encrypt` / `aes_128_ctr_encrypt` | **Rust** (`aes_ctr.rs`); C TU removed (W1-03) |
//! | `omac1_aes_*` | **Rust** (`aes_omac1.rs`); C TU removed (W2-01) |
//! | `gcmp_*` | **Rust** (`gcmp.rs`); C TU removed (W2-02) |
//! | `aes_siv_*` | **Rust** (`aes_siv.rs`); C TU removed (W2-03) |
//! | `aes_ccm_*` | **Rust** (`aes_ccm.rs`); C TU removed (W2-04) |
//! | `sha256_vector` / `_sha256_*` | **Rust** (`sha256_internal.rs`); C TU removed (W2-05) |
//! | `sha256_prf` / `sha256_prf_bits` | **Rust** (`sha256_prf.rs`); C TU removed (W2-06) |
//! | `os_memcmp_const` / `os_memdup` / `rtw_registrypriv_amsdu_mode` / `wpa_*` | **Rust** (`rtw_crypto_wrap.rs`); C TU removed (W2-06) |
//! | `hmac_sha256_vector` | **C** (`sha256.c`) | Rust binds until W2-16 |
//! | Remaining `core/crypto/*.c` + rest of driver | **C** | Until later waves claim them |
//!
//! ## Rules
//!
//! 1. **Bind ≠ own.** Allowlisted bindgen entries are for symbols **C still
//!    defines**. Rust must not also provide those symbols in the same link.
//! 2. **Own ⇒ remove C defs.** When Rust takes a symbol (e.g. W1-03 `aes_ctr_*`),
//!    drop the C TU (or extract the defs) from the Makefile object list first.
//! 3. **Shims stay thin.** `extern "C"` wrappers for C callers convert to/from
//!    domain types at this edge; typed logic belongs in future `domain/` code.
//! 4. **Shrink over time.** When the last C caller of a shim goes away, delete
//!    the shim and call the typed Rust API directly (Phase 2 / later waves).

#![allow(
    dead_code,
    improper_ctypes,
    missing_docs,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    unused_imports
)]

/// Allowlisted bindgen output for C-owned AES leaf symbols.
///
/// Regenerated by `./scripts/bindgen_rtw.sh` into `rust/bindings/generated.rs`.
mod bindings {
    include!("bindings/generated.rs");
}

pub use bindings::*;

/// Link-time probe: returns `AES_BLOCK_SIZE` from the re-exported bindings.
///
/// Confirms the FFI/bindings object is present in `88x2bu.ko` (`nm` / L1).
#[no_mangle]
pub extern "C" fn rtw_rust_bindings_probe() -> core::ffi::c_int {
    AES_BLOCK_SIZE as core::ffi::c_int
}
