#!/usr/bin/env bash
# File draft issues from docs/rust-migration/issues/*.md onto GitHub.
# Requires: Issues enabled on the repo; gh authenticated with issue write scope.
set -euo pipefail

ISSUE_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$ISSUE_DIR/../../.." && pwd)"
MAP_FILE="$ISSUE_DIR/ISSUE-MAP.md"
REPO="${GITHUB_REPOSITORY:-$(gh repo view --json nameWithOwner -q .nameWithOwner)}"

if ! gh api "repos/$REPO" --jq .has_issues | grep -q true; then
  echo "ERROR: Issues are disabled on $REPO." >&2
  echo "Enable them: GitHub → Settings → General → Features → Issues" >&2
  echo "Then re-run: $0" >&2
  exit 1
fi

labels=(
  rust-migration
  phase-1
  phase-2
  wave-0 wave-1 wave-2 wave-3 wave-4 wave-5 wave-6
  "size/~200"
)

echo "Ensuring labels on $REPO..."
for label in "${labels[@]}"; do
  color=0E8A16
  case "$label" in
    phase-2) color=5319E7 ;;
    wave-*) color=1D76DB ;;
    size/*) color=FBCA04 ;;
    rust-migration) color=B60205 ;;
  esac
  gh label create "$label" --repo "$REPO" --color "$color" --force >/dev/null
done

files=(
  epic-01-phase1.md
  epic-02-wave0.md
  epic-03-wave1.md
  epic-04-wave2.md
  epic-05-wave3.md
  epic-06-wave4.md
  epic-07-wave5.md
  epic-08-wave6.md
  epic-09-phase2.md
  wave0-01-docs.md
  wave0-02-kbuild.md
  wave0-03-scaffold.md
  wave1-01-bindgen.md
  wave1-02-ffi-module.md
  wave1-03-pilot-aes-ctr.md
  wave1-04-pilot-makefile-smoke.md
  wave2-01-aes-omac1.md
  wave2-02-gcmp.md
  wave2-03-aes-siv.md
  wave2-04-aes-ccm.md
  wave2-05-sha256-internal.md
  wave2-06-sha256-prf-wrap.md
  wave2-07-aes-gcm-part1.md
  wave2-08-aes-gcm-part2.md
  wave2-09-ccmp-part1.md
  wave2-10-ccmp-part2.md
  wave2-11-aes-internal-part1.md
  wave2-12-aes-internal-part2.md
  wave2-13-aes-internal-part3.md
  wave2-14-aes-internal-part4.md
  wave2-15-aes-internal-enc.md
  wave2-16-sha256.md
)

echo "# Issue map" >"$MAP_FILE"
echo "" >>"$MAP_FILE"
echo "Generated by \`docs/rust-migration/issues/file-issues.sh\` on $(date -u +%Y-%m-%dT%H:%MZ)." >>"$MAP_FILE"
echo "" >>"$MAP_FILE"
echo "| Draft ID | GitHub | Title |" >>"$MAP_FILE"
echo "|----------|--------|-------|" >>"$MAP_FILE"

extract_field() {
  local file="$1" key="$2"
  sed -n "/^---$/,/^---$/p" "$file" | sed -n "s/^${key}:[[:space:]]*//p" | head -1
}

body_without_frontmatter() {
  local file="$1"
  awk 'BEGIN{fm=0} /^---$/{fm++; next} fm>=2{print}' "$file"
}

for f in "${files[@]}"; do
  path="$ISSUE_DIR/$f"
  title="$(extract_field "$path" title | sed 's/^"//;s/"$//')"
  labels_csv="$(extract_field "$path" labels)"
  id="$(extract_field "$path" id)"
  label_args=()
  labels_csv="${labels_csv#\[}"
  labels_csv="${labels_csv%\]}"
  IFS=',' read -ra raw_labels <<<"$labels_csv"
  for lab in "${raw_labels[@]}"; do
    lab="$(echo "$lab" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    [[ -n "$lab" ]] && label_args+=(--label "$lab")
  done

  body="$(body_without_frontmatter "$path")"
  echo "Creating: $title"
  url="$(gh issue create --repo "$REPO" --title "$title" --body "$body" "${label_args[@]}")"
  num="${url##*/}"
  echo "| $id | #$num | $title |" >>"$MAP_FILE"
  echo "  -> $url"
done

echo ""
echo "Done. Map written to $MAP_FILE"
