#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0
#
# Regenerate allowlisted Rust bindings for the Wave 1 crypto pilot.
#
# Usage (from repo root):
#   ./scripts/bindgen_rtw.sh
#   KDIR=/path/to/rust-enabled-kernel ./scripts/bindgen_rtw.sh
#
# Environment:
#   KDIR            Pinned Rust-enabled kernel tree (default: /opt/linux).
#                   Used for clang --sysroot / resource-dir consistency with L0.
#   BINDGEN         bindgen binary (default: bindgen on PATH).
#   LIBCLANG_PATH   Optional; set if bindgen cannot find libclang.
#
# Output:
#   rust/bindings/generated.rs
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KDIR="${KDIR:-/opt/linux}"
BINDGEN_BIN="${BINDGEN:-bindgen}"
HELPER="${REPO_ROOT}/rust/bindings/bindgen_helper.h"
OUT="${REPO_ROOT}/rust/bindings/generated.rs"
TMP_OUT="$(mktemp)"
trap 'rm -f "${TMP_OUT}"' EXIT

if ! command -v "${BINDGEN_BIN}" >/dev/null 2>&1; then
	echo "error: bindgen not found (install bindgen-cli 0.65.1; see docs/rust-migration/dev-environment.md)" >&2
	exit 1
fi

if [[ ! -f "${HELPER}" ]]; then
	echo "error: missing helper header: ${HELPER}" >&2
	exit 1
fi

# Prefer the pinned kernel's clang resource directory when available so
# bindgen's libclang matches the L0 LLVM=1 toolchain.
CLANG_RESOURCE_DIR=""
if command -v clang >/dev/null 2>&1; then
	CLANG_RESOURCE_DIR="$(clang -print-resource-dir 2>/dev/null || true)"
fi

CLANG_ARGS=(
	"-I${REPO_ROOT}/rust/bindings"
	"-D__BINDGEN__"
)
if [[ -n "${CLANG_RESOURCE_DIR}" ]]; then
	CLANG_ARGS+=("-resource-dir=${CLANG_RESOURCE_DIR}")
fi
# KDIR is reserved for future headers that need kernel include paths; for the
# aes.h pilot surface we only need freestanding C types. Still require KDIR to
# exist so regenerate stays tied to the Wave 0 pinned-kernel contract.
if [[ ! -d "${KDIR}" ]]; then
	echo "error: KDIR not a directory: ${KDIR}" >&2
	echo "hint: build/pin a Rust-enabled kernel per docs/rust-migration/dev-environment.md" >&2
	exit 1
fi

echo "bindgen: helper=${HELPER}"
echo "bindgen: KDIR=${KDIR}"
echo "bindgen: out=${OUT}"

# Allowlist keeps review tractable: only AES leaf symbols the pilot needs.
# Do not allowlist aes_ctr_* — those will be *defined* by the Rust pilot (W1-03).
#
# Note: no crate-level #![...] in the generated file — it is include!'d from
# rust/bindings.rs (inner attributes belong on that crate root).
"${BINDGEN_BIN}" \
	"${HELPER}" \
	--rust-target 1.68 \
	--use-core \
	--ctypes-prefix core::ffi \
	--no-layout-tests \
	--no-doc-comments \
	--allowlist-function 'aes_encrypt.*' \
	--allowlist-function 'aes_decrypt.*' \
	--allowlist-var 'AES_BLOCK_SIZE' \
	--raw-line '/* SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause */' \
	--raw-line '/* @generated by scripts/bindgen_rtw.sh — do not edit by hand. */' \
	-o "${TMP_OUT}" \
	-- \
	"${CLANG_ARGS[@]}"

mv "${TMP_OUT}" "${OUT}"
trap - EXIT

echo "bindgen: wrote $(wc -l < "${OUT}") lines to ${OUT}"
