#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0
#
# Regenerate allowlisted Rust bindings for the Wave 1 crypto pilot.
#
# Usage (from repo root):
#   ./scripts/bindgen_rtw.sh
#   ./scripts/bindgen_rtw.sh --check          # fail if committed blob is stale
#   CHECK=1 ./scripts/bindgen_rtw.sh          # same as --check
#   KDIR=/path/to/rust-enabled-kernel ./scripts/bindgen_rtw.sh
#
# Environment:
#   KDIR            Pinned Rust-enabled kernel tree (default: /opt/linux).
#                   Wave 0 contract pin: must exist so regenerate stays tied to
#                   the same kernel used for L0. Not passed to clang yet — the
#                   aes.h pilot surface only needs freestanding C types; future
#                   waves may add kernel include paths here.
#   BINDGEN         bindgen binary (default: bindgen on PATH).
#   LIBCLANG_PATH   Optional; set if bindgen cannot find libclang.
#   CHECK           If set to 1, verify without writing (see --check).
#
# Output:
#   rust/bindings/generated.rs
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KDIR="${KDIR:-/opt/linux}"
BINDGEN_BIN="${BINDGEN:-bindgen}"
HELPER="${REPO_ROOT}/rust/bindings/bindgen_helper.h"
OUT="${REPO_ROOT}/rust/bindings/generated.rs"

CHECK_MODE=0
if [[ "${CHECK:-0}" == "1" ]]; then
	CHECK_MODE=1
fi
for arg in "$@"; do
	case "${arg}" in
	--check) CHECK_MODE=1 ;;
	-h | --help)
		sed -n '2,28p' "$0"
		exit 0
		;;
	*)
		echo "error: unknown argument: ${arg}" >&2
		echo "usage: $0 [--check]" >&2
		exit 1
		;;
	esac
done

TMP_OUT="$(mktemp)"
trap 'rm -f "${TMP_OUT}"' EXIT

if ! command -v "${BINDGEN_BIN}" >/dev/null 2>&1; then
	echo "error: bindgen not found (install bindgen-cli 0.65.1; see docs/rust-migration/dev-environment.md)" >&2
	exit 1
fi

if [[ ! -f "${HELPER}" ]]; then
	echo "error: missing helper header: ${HELPER}" >&2
	exit 1
fi

# Prefer the pinned kernel's clang resource directory when available so
# bindgen's libclang matches the L0 LLVM=1 toolchain.
CLANG_RESOURCE_DIR=""
if command -v clang >/dev/null 2>&1; then
	CLANG_RESOURCE_DIR="$(clang -print-resource-dir 2>/dev/null || true)"
fi

CLANG_ARGS=(
	"-I${REPO_ROOT}/rust/bindings"
	"-I${REPO_ROOT}/core/crypto"
	"-D__BINDGEN__"
)
if [[ -n "${CLANG_RESOURCE_DIR}" ]]; then
	CLANG_ARGS+=("-resource-dir=${CLANG_RESOURCE_DIR}")
fi

# Wave 0 pinned-kernel contract (existence only for this pilot surface).
if [[ ! -d "${KDIR}" ]]; then
	echo "error: KDIR not a directory: ${KDIR}" >&2
	echo "hint: build/pin a Rust-enabled kernel per docs/rust-migration/dev-environment.md" >&2
	exit 1
fi

echo "bindgen: helper=${HELPER}"
echo "bindgen: KDIR=${KDIR} (pin only; not passed to clang for aes.h surface)"
echo "bindgen: out=${OUT}"

# Allowlist keeps review tractable: only AES leaf symbols the pilot needs.
# Do not allowlist aes_ctr_* — those will be *defined* by the Rust pilot (W1-03).
#
# Note: no crate-level #![...] in the generated file — it is include!'d from
# rust/bindings.rs (inner attributes belong on that crate root).
"${BINDGEN_BIN}" \
	"${HELPER}" \
	--rust-target 1.68 \
	--use-core \
	--ctypes-prefix core::ffi \
	--no-layout-tests \
	--no-doc-comments \
	--allowlist-function 'aes_encrypt.*' \
	--allowlist-function 'aes_decrypt.*' \
	--allowlist-var 'AES_BLOCK_SIZE' \
	--raw-line '/* SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause */' \
	--raw-line '/* @generated by scripts/bindgen_rtw.sh — do not edit by hand. */' \
	-o "${TMP_OUT}" \
	-- \
	"${CLANG_ARGS[@]}"

if [[ "${CHECK_MODE}" -eq 1 ]]; then
	if [[ ! -f "${OUT}" ]]; then
		echo "error: missing committed bindings: ${OUT}" >&2
		exit 1
	fi
	if ! diff -u "${OUT}" "${TMP_OUT}"; then
		echo "error: ${OUT} is stale; run ./scripts/bindgen_rtw.sh and commit the result" >&2
		exit 1
	fi
	echo "OK: ${OUT} matches bindgen output"
	exit 0
fi

mv "${TMP_OUT}" "${OUT}"
trap - EXIT

echo "bindgen: wrote $(wc -l < "${OUT}") lines to ${OUT}"
