#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0
#
# Regenerate allowlisted Rust bindings for the crypto pilot (W1-01).
#
# Usage (from repo root):
#   ./scripts/bindgen_rtw.sh
#
# Requires bindgen-cli 0.65.x on PATH (kernel-pinned; see
# docs/rust-migration/dev-environment.md). LIBCLANG_PATH should point at the
# Clang used for LLVM=1 builds when not discoverable automatically.
#
# Output: rust/bindings/bindings_generated.rs (committed; re-run after changing
# the helper header or allowlists below).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HELPER="${ROOT}/rust/bindings/bindgen_helper.h"
OUT="${ROOT}/rust/bindings/bindings_generated.rs"

BINDGEN="${BINDGEN:-bindgen}"

if ! command -v "${BINDGEN}" >/dev/null 2>&1; then
	echo "error: bindgen not found on PATH (install bindgen-cli 0.65.1 --locked)" >&2
	exit 1
fi

# Match kernel rust/Makefile bindgen baseline where practical.
# Allowlist: AES encrypt API + AES_BLOCK_SIZE only (pilot callers of aes-ctr).
# Decrypt symbols in aes.h stay excluded until a later chunk needs them.
"${BINDGEN}" \
	"${HELPER}" \
	--rust-target 1.68 \
	--use-core \
	--ctypes-prefix core::ffi \
	--no-layout-tests \
	--no-doc-comments \
	--allowlist-function '^aes_encrypt$' \
	--allowlist-function '^aes_encrypt_init$' \
	--allowlist-function '^aes_encrypt_deinit$' \
	--allowlist-var '^AES_BLOCK_SIZE$' \
	-o "${OUT}" \
	-- \
	-I"${ROOT}/core/crypto" \
	-D__BINDGEN__

# Prepend a short provenance banner (bindgen overwrites the file).
tmp="$(mktemp)"
{
	cat <<'EOF'
/* automatically generated by scripts/bindgen_rtw.sh — do not edit by hand */
/* W1-01 allowlisted bindings: AES encrypt API for the aes-ctr pilot */

EOF
	# Drop bindgen's identical first line if present, keep the rest.
	if head -n1 "${OUT}" | grep -q 'automatically generated by rust-bindgen'; then
		tail -n +2 "${OUT}"
	else
		cat "${OUT}"
	fi
} >"${tmp}"
mv "${tmp}" "${OUT}"

echo "Wrote ${OUT}"
